#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# We use an image that has our repository already using.
# Let's go back to using original pacman.conf.
rm /etc/pacman.conf
cp /etc/pacman.conf.orig /etc/pacman.conf

pacman -Syu --noconfirm

if [ -e packages ]; then
  rm -r packages
fi
mkdir packages

curl https://gist.githubusercontent.com/pauldotknopf/ff8e986225ab2f264acea1a5bb0c6c5a/raw/5c26a163f7815682793001312b0bd693bebb3d45/makepkg.patch | patch /usr/bin/makepkg

build_package() {
  trizen -S --skipinteg --movepkg --movepkg-dir=packages --noconfirm --noedit --clone-dir="${HOME}/tmp" $1
}

build_package nerd-fonts-complete
build_package ttf-ms-fonts
build_package ttf-hack-powerline-git
build_package ttf-font-awesome-4
build_package pulseaudio-ctl
build_package libcgroup
build_package autorandr-git
build_package rambox-bin
build_package polybar
build_package visual-studio-code-bin
build_package google-chrome

repo-add packages/johannesfrey.db.tar.gz packages/*.pkg.tar.xz
